apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata: 
  name: multi-k8s-cf-tls
spec:
  secretName: multi-k8s-cf
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.cf
  dnsNames:
    - multi-k8s.cf
    - www.multi-k8s.cf
  acme:
    config: 
      - http01:
          ingressClass: nginx
        domains:
          - multi-k8s.cf
          - www.multi-k8s.cf

